services:
  mc:
    build:
      dockerfile: Dockerfile.paper
      context: build_image
      args:
	# Find the values from: https://papermc.io/downloads/paper
        version: 1.20.6
        build: 137
    container_name: minecraft_paper
    environment:
      EULA: "true"
      InitRAM: "3g"
      MaxRAM: "10g"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
