services:
  mc:
    build:
      dockerfile: Dockerfile.paper
      context: build_image
      args:
        version: 1.20.6
        build: 137
    container_name: minecraft_paper
    env_file:
      - env.list
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
